import { Dataset } from '@/types'

const PlaceHolderDatasets: Dataset[] = [
    {
      id: '1',
      title: 'MNIST Dataset',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non velit sed metus venenatis rutrum. Mauris eget pellentesque odio, non convallis nisi. Curabitur dignissim nulla et mauris efficitur, sodales vestibulum risus laoreet. Pellentesque posuere nisl et erat tristique luctus. Proin mattis pharetra consectetur. Duis tempor egestas mauris non facilisis. Vestibulum ac erat pharetra, lacinia mauris sed, interdum enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi dui nunc, suscipit ac laoreet eu, sollicitudin nec orci. Morbi posuere erat vitae sem ullamcorper finibus. Etiam fermentum ornare urna, quis scelerisque tortor congue sed.',
      category: 'Dataset',
      subcategory: 'CV',
      uploader: 'John Doe',
      dateAdded: '2023-05-01',
      downloads: 1000,
      tags: ['machine learning', 'computer vision'],
      datasetSize: '11.5 MB',
      fileFormat: 'CSV',
      views: 5000,
      likes: 500,
      dislikes: 50,
      source: 'https://example.com/sample-item',
    },
    {
      id: '2',
      title: 'ImageNet',
      description: 'Large-scale image recognition dataset',
      category: 'Dataset',
      subcategory: 'CV',
      uploader: 'Jane Smith',
      dateAdded: '2023-04-15',
      downloads: 5000,
      tags: ['computer vision', 'deep learning'],
      datasetSize: '150 GB',
      fileFormat: 'JPEG',
      views: 10000,
      likes: 1000,
      dislikes: 100,
      source: 'https://example.com/sample-item',
    },
    {
      id: '3',
      title: 'CIFAR-10',
      description: 'Object recognition dataset',
      category: 'Dataset',
      subcategory: 'CV',
      uploader: 'Alice Johnson',
      dateAdded: '2023-06-01',
      downloads: 2000,
      tags: ['computer vision', 'deep learning'],
      datasetSize: '60 MB',
      fileFormat: 'PNG',
      views: 8000,
      likes: 800,
      dislikes: 80,
      source: 'https://example.com/sample-item',
    },
    {
      id: '4',
      title: 'IMDB Movie Reviews',
      description: 'Sentiment analysis dataset',
      category: 'Dataset',
      subcategory: 'NLP',
      uploader: 'Bob Brown',
      dateAdded: '2023-07-01',
      downloads: 3000,
      tags: ['natural language processing', 'sentiment analysis'],
      datasetSize: '25 MB',
      fileFormat: 'TXT',
      views: 6000,
      likes: 600,
      dislikes: 60,
      source: 'https://example.com/sample-item',
    },
    {
      id: '5',
      title: 'Wikipedia Text',
      description: 'Text classification dataset',
      category: 'Dataset',
      subcategory: 'NLP',
      uploader: 'Eve Green',
      dateAdded: '2023-07-15',
      downloads: 1500,
      tags: ['natural language processing', 'text classification'],
      datasetSize: '100 MB',
      fileFormat: 'TXT',
      views: 7000,
      likes: 700,
      dislikes: 70,
      source: 'https://example.com/sample-item',
    },
    {
      id: '6',
      title: 'Spam Email Dataset',
      description: 'Email spam detection dataset',
      category: 'Dataset',
      subcategory: 'NLP',
      uploader: 'Charlie White',
      dateAdded: '2023-08-01',
      downloads: 2500,
      tags: ['natural language processing', 'email spam'],
      datasetSize: '5 MB',
      fileFormat: 'CSV',
      views: 9000,
      likes: 900,
      dislikes: 90,
      source: 'https://example.com/sample-item',
    },
    {
      id: '7',
      title: 'Fashion MNIST',
      description: 'Clothing classification dataset',
      category: 'Dataset',
      subcategory: 'CV',
      uploader: 'David Black',
      dateAdded: '2023-09-01',
      downloads: 4000,
      tags: ['computer vision', 'clothing classification'],
      datasetSize: '15 MB',
      fileFormat: 'CSV',
      views: 4000,
      likes: 400,
      dislikes: 40,
      source: 'https://example.com/sample-item',
    },
    {
      id: '8',
      title: 'Yelp Reviews',
      description: 'Review sentiment analysis dataset',
      category: 'Dataset',
      subcategory: 'NLP',
      uploader: 'Frank Gray',
      dateAdded: '2023-10-01',
      downloads: 3500,
      tags: ['natural language processing', 'review sentiment'],
      datasetSize: '30 MB',
      fileFormat: 'TXT',
      views: 3000,
      likes: 300,
      dislikes: 30,
      source: 'https://example.com/sample-item',
    },
    {
      id: '9',
      title: 'COCO Dataset',
      description: 'Common Objects in Context dataset',
      category: 'Dataset',
      subcategory: 'CV',
      uploader: 'Grace Brown',
      dateAdded: '2023-11-01',
      downloads: 6000,
      tags: ['computer vision', 'object detection'],
      datasetSize: '200 GB',
      fileFormat: 'JSON',
      views: 2000,
      likes: 200,
      dislikes: 20,
      source: 'https://example.com/sample-item',
    },
    {
      id: '10',
      title: 'Twitter Sentiment',
      description: 'Social media sentiment analysis dataset',
      category: 'Dataset',
      subcategory: 'NLP',
      uploader: 'Harry Green',
      dateAdded: '2023-12-01',
      downloads: 4500,
      tags: ['natural language processing', 'social media'],
      datasetSize: '50 MB',
      fileFormat: 'CSV',
      views: 5000,
      likes: 500,
      dislikes: 50,
      source: 'https://example.com/sample-item',
    },
  ]

export default PlaceHolderDatasets